<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 yellow-rubber-duck/source/Yellow rubber duck/Rubbish_Duck.gltf --transform
-->

<script>
  import { Group } from "three";
  import { T } from "@threlte/core";
  import { useGltf } from "@threlte/extras";

  export const ref = new Group();

  const gltf = useGltf("/Rubbish_Duck-transformed.glb", { useDraco: true });
</script>

<T is={ref} dispose={false} {...$$restProps}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Cube015.geometry}
      material={gltf.materials["Yellow texture"]}
      position={[0, 0.58, -0.04]}
      scale={0.42}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube012.geometry}
      material={gltf.materials["Yellow texture"]}
      position={[0, 0.87, 0.45]}
      scale={0.42}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube013.geometry}
      material={gltf.materials["Yellow texture"]}
      position={[0, 0.78, 0.45]}
      scale={0.42}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
