<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 yellow_rubber_duck.glb
Author: Orex (https://sketchfab.com/oresinaleksandr4)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/yellow-rubber-duck-1990cda4c97e400f852d2b4078ebb958
Title: Yellow rubber duck🐥
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/yellow_rubber_duck.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Object_4.geometry}
      material={gltf.materials.Yellow_texture}
      position={[0, 0.58, -0.04]}
      scale={0.42}
    />
    <T.Mesh
      geometry={gltf.nodes.Object_6.geometry}
      material={gltf.materials.Yellow_texture}
      position={[0, 0.87, 0.45]}
      scale={0.42}
    />
    <T.Mesh
      geometry={gltf.nodes.Object_8.geometry}
      material={gltf.materials.Yellow_texture}
      position={[0, 0.78, 0.45]}
      scale={0.42}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
